#!/usr/bin/env python3
"""Build the private, concrete final integration map after every required result."""
import pathlib,json,hashlib,time
own=pathlib.Path(__file__).resolve().parent;root=own.parents[2];docs=root/'docs/research/candidate-study';pub=docs/'publication'
def read(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def item(p):return {'path':p.relative_to(root).as_posix(),'sha256':sha(p),'bytes':p.stat().st_size}
manifest=pub/'evidence-manifest-final.json';m=read(manifest);analysis=read(pub/'tables/final/analysis.json');assert len(m['studies'])==8 and analysis['status']=='PASS' and analysis['native_offered']==1984
studies=[]
for entry in m['studies']:
 sid=entry['id'];study=own/sid;export=own/sid.replace('-study','-export');audit=own/(sid.replace('-study','-raw-audit')+'.json');report=own/(sid.replace('-study','-report')+'.json');queue=read(own/(sid+'.queue')/'receipt.json');a=read(audit)
 assert (export/'EXPORT-READY.json').is_file() and a['status']=='PASS' and queue['status']=='COMPLETED' and queue['exit_code']==0
 assert queue['finished_ns']<=310468865220540
 studies.append({'safe_package_study_id':('clarification-05b-study04' if sid=='clarification-0.5b-study04' else sid),'original_study_id':sid,'export_path':export.relative_to(root).as_posix(),'native_study_path':study.relative_to(root).as_posix(),'queue_receipt':item(own/(sid+'.queue')/'receipt.json'),'raw_audit':item(audit),'native_report':item(report),'export_ready':item(export/'EXPORT-READY.json'),'producer_archive_sha256':queue['archive_sha256']})
assert analysis['native_execution_s']<=10800
assets=pub/'reviewed-assets-final.json';assert assets.is_file()
for relative,digest in read(assets).items():assert sha(root/relative)==digest
spec={'title':'Symbolic closure preserves task semantics but not native answers: a bounded context-selection investigation','classification':'NEGATIVE_ENGINEERING_STUDY','source_directory':'docs/research/candidate-study','entrypoint':'docs/research/candidate-study/manuscript.md','studies':[s['safe_package_study_id'] for s in studies]}
spec_path=own/'candidate-research-spec04.json';spec_path.write_text(json.dumps(spec,indent=2)+'\n')
operator={'schema_version':1,'status':'COMPLETE','created_ns':time.monotonic_ns(),'native_cwd':str(root),'native_executor':'tools/run_queued_recipe.py','native_execution_note':'Execute packaged producer/recipe bytes from the main workspace cwd under the unchanged original allocation; use new reviewer output directories. Do not introduce a nested WORKSPACE marker.','confirmation_runtime':{'server':'.cache/prepared-20260908-01/build/bin/llama-server','model':'.cache/prepared-20260908-01/qwen2.5-0.5b-instruct-fp16.gguf','setup':'.cache/adopted-0.5b-current-02/setup.json','model_profile_id':'qwen2.5-0.5b-instruct-fp16-v2','model_profile_sha256':'13e85926dcbbf56e3004f3c72b8375d1b921355c15579ee92bb8bf141a5396e4','producer':item(root/'.cache/packaged-v1-platform-20260908-04/lean-model-lab.pyz')},'original_confirmation_recipes':[item(own/('negative-confirm-'+policy+'-recipe04.json')) for policy in ['slice','simple','learned']],'studies':studies,'publication':{'research_spec':item(spec_path),'manuscript':item(docs/'manuscript.md'),'portable_guide':item(docs/'PUBLICATION-RERUN.md'),'final_manifest':item(manifest),'reviewed_asset_map':item(assets),'portable_validation':item(pub/'portable-export-check-final.json'),'training_validation':item(pub/'portable-training-validation-final.json'),'source_boundary_validation':item(pub/'source-boundary-check-final.json'),'memory_and_timing_summary':item(pub/'tables/final/memory-and-timing-summary.json')},'native_budget':{'actual_offered':analysis['native_offered'],'actual_execution_s':analysis['native_execution_s'],'execution_definition':'Archive-process receipt finished_ns minus execution_started_ns; excludes shared-queue waiting, retained separately inside original-allocation elapsed time.','maximum_offered':2000,'maximum_native_execution_s':10800,'original_deadline_ns':310468865220540,'scope':'Candidate original campaign only; future separately assigned reproduction has its own cap within the same original allocation.'},'claims':{'controller_mode':read(pub/'artifacts/training/controller.json')['parameters']['mode'],'unique_original_tables':analysis['unique_record_bodies_across_studies'],'classification':'NEGATIVE_ENGINEERING_STUDY','no_eligible_efficiency_claim':True,'no_formal_population_risk_guarantee':True,'no_llm_training_or_new_architecture':True}}
target=own/'candidate-operator-map04.json';target.write_text(json.dumps(operator,indent=2)+'\n');print(json.dumps({'operator_map':str(target.relative_to(root)),'sha256':sha(target),'spec':str(spec_path.relative_to(root)),'native_offered':analysis['native_offered'],'native_execution_s':analysis['native_execution_s']}))
