from pathlib import Path
import json,hashlib,shutil,csv,time
own=Path(__file__).resolve().parent;root=own.parents[2];docs=root/'docs/research/candidate-study';pub=docs/'publication';stage=own/'portable-export-test04'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2)+'\n')
analysis=stage/'analysis-final';a=json.loads((analysis/'analysis.json').read_text());assert a['native_offered']==1984 and a['status']=='PASS'
out=pub/'tables/final';out.mkdir(exist_ok=True);derivatives=[]
for p in analysis.iterdir():
 raw=p.read_bytes();data=raw.replace(str(stage).encode(),b'$EVIDENCE_ROOT');target=out/p.name;target.write_bytes(data)
 if data!=raw:derivatives.append({'artifact':target.relative_to(root).as_posix(),'original_sha256':sha(p),'derived_sha256':sha(target),'operation':'Operational evidence-root text replaced with $EVIDENCE_ROOT; scientific values unchanged.'})
shutil.copytree(stage/'illustrations-final',pub/'artifacts/confirmation-illustrations-final',dirs_exist_ok=True)
shutil.copy2(stage/'training-validation-final.json',pub/'portable-training-validation-final.json')
shutil.copytree(own/'pdf-review-confirmation-final-v2',docs/'figures/pdf-review-confirmation',dirs_exist_ok=True)
assets={p.relative_to(root).as_posix():sha(p) for p in sorted((docs/'figures').rglob('*')) if p.suffix in ['.png','.pdf']}
dump(pub/'reviewed-assets-final.json',assets);dump(pub/'reviewed-assets-current.json',assets)
dump(pub/'pdf-visual-review-final.json',{'status':'PASS','recorded_ns':time.monotonic_ns(),'scope':'All three final confirmation PNGs and independently PDFium-rendered actual PDFs visually inspected. Titles, legends, labels, counts and hatches readable with no overlaps. Four closed/development PNGs match previously reviewed bytes exactly; original reviewed PDFs retained.','reviewed_assets':assets,'initial_renderer_environment_note':'Initial system-Python PDF rendering lacked Pillow. Retried successfully in the existing locked plotting environment with the same PDFium installation; scientific data and figures were unchanged.'})
script_ids={p.name:sha(p) for p in (pub/'scripts').glob('*.py')}
for name in ['reanalyze.py','validate_training.py','illustrations.py','plot.py']:
 assert sha(pub/'scripts'/name)==sha(stage/'lean-model-lab-source/docs/research/candidate-study/publication/scripts'/name)
dump(pub/'portable-export-check-final.json',{'status':'PASS','native_offered':1984,'actual_exports':8,'unique_original_tables':200,'native_execution_s':a['native_execution_s'],'manifest_sha256':sha(pub/'evidence-manifest-final.json'),'executed_staged_scripts':script_ids,'original_analysis_sha256':sha(analysis/'analysis.json'),'training_validation_sha256':sha(stage/'training-validation-final.json'),'illustration_receipt_sha256':sha(stage/'illustrations-final/selection-receipt.json'),'operational_derivatives':derivatives,'scope':'Executed staged scripts against all eight actual exported studies in complete-builder layout, plus both original producer files. Reanalysis, native training reconciliation, prospective illustration selection with raw SSE reconstruction and all seven plots completed; no native inference. Four prior PNGs reproduced byte-exactly; final PNG and actual PDF-render visual review recorded separately.'})
parts={
'CONFIRMATION_ABSTRACT':'''A dependency-closure certificate can preserve a record program's exact answer while changing a model's answer from correct to wrong. We tested this boundary in a bounded native investigation using an authored 24-record language and Qwen2.5-0.5B-Instruct FP16. On 128 fresh mixed-family confirmation tables, full context answered 23/128 correctly and always dependency slicing answered 34/128 in each of two arm-order-balanced repetitions. Their complete paired classes were 10 both correct, 13 harmed by slicing, 24 benefited and 81 jointly wrong. A fixed simple gate scored 24/128, harming 11 and benefiting 12; the fitted controller refused all omissions and scored the same 23/128 as full context. No arm reached the unchanged 95% quality floor. Even a conditional oracle restricted to the observed full/slice outputs reached only 47/128 (36.72%), in each pair and under a conservative repeated-output rule. Slicing reduced prompt tokens and descriptive wall time, but produced no eligible quality-preserving efficiency result.''',
'CONFIRMATION_TABLE':'''Counts below apply separately to AB and BA: all per-question correctness classes repeat exactly. Each row retains all 128 offered questions; repetitions do not double the independent table count.

| Native candidate policy | Full correct | Candidate correct | Both correct | Full only: harm | Candidate only: benefit | Both wrong | Observed oracle |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Always dependency slice | 23 | 34 | 10 | 13 | 24 | 81 | 47 |
| Fixed simple gate | 23 | 24 | 12 | 11 | 12 | 93 | 35 |
| Fitted controller: all full | 23 | 23 | 23 | 0 | 0 | 105 | 23 |

![Quality and descriptive deployment cost for the complete confirmation matrix](figures/confirmation/confirmation-quality-and-cost.png)

![All four native correctness classes, with every offered question retained](figures/confirmation/confirmation-four-outcomes.png)''',
'CONFIRMATION_INTERPRETATION':'''Always slicing improves aggregate exact accuracy from 17.97% to 26.56%, while damaging 13 individually correct answers. Thus aggregate nonregression and per-question harm are distinct. The simple gate accepts the 43 direct lookups and falls back on the other 85 tables; its 18.75% accuracy still includes 11 harmed lookups. The deployed native controller has 128 `IDENTITY` decisions per repetition and 17.97% accuracy. All dependency and gated prompts independently preserve the symbolic answer. Every arm fails the 95% quality floor, including the unchanged full baselines; all product eligibility decisions are false. The learned fallback prevents omission but cannot repair baseline incompetence.''',
'ORACLE_RESULTS':'''The full/slice conditional oracle is 47/128 (36.72%); the full/simple oracle is 35/128 (27.34%); the full/fitted oracle is 23/128 (17.97%). Each value holds separately in both repetitions and for the conservative rule. No oracle reaches 95%. For slicing, the mixed population separates as follows:

| Family | Offered | Both correct | Harm | Benefit | Both wrong | Oracle correct |
| --- | ---: | ---: | ---: | ---: | ---: | ---: |
| Direct lookup | 43 | 10 | 11 | 12 | 10 | 33 |
| Reference chain | 43 | 0 | 1 | 4 | 38 | 5 |
| Updates | 42 | 0 | 1 | 8 | 33 | 9 |

These counts also repeat exactly. The direct-lookup oracle is 76.74%, versus 11.63% for reference chains and 21.43% for updates. Removing the harder families would change the prospectively offered population and still would not make the retained lookup outputs meet 95%.

![Complete slice outcomes by offered family](figures/confirmation/slice-family-outcomes.png)''',
'CONFIRMATION_ILLUSTRATIONS':'''The prospectively frozen rule selects `r009`, the first harmful direct lookup in both repetitions: original line `VALUE COWPG CGMSA` with query `ASK COWPG` resolves to `CGMSA`. The full native answer is `CGMSA`; the certified one-record slice answers `COWPG`, copying the key. Both native streams stop at EOS after four generated tokens, including EOS, with neither truncation nor cross-request prefix reuse. Full and sliced prompt counts are 269 and 92 tokens. This is a complete-response error on a direct lookup, without reference indirection or overwrite ambiguity.

The first repeated benefit is `r003`: `VALUE COUKW CAMYD` with query `ASK COUKW` has answer `CAMYD`. Full outputs `COKSW`, while slicing outputs `CAMYD`, both ending at EOS. The selector considered 13 repeated harms, including 11 lookups, and 24 repeated benefits, including 12 lookups; it did not select solely from these two displayed cases. The [harmful case](publication/artifacts/confirmation-illustrations-final/harmful-r009.md), [beneficial case](publication/artifacts/confirmation-illustrations-final/beneficial-r003.md) and adjacent JSON artifacts retain complete prompts, both repetitions, certificates, native stream identities and token-level reconstruction. The [selection receipt](publication/artifacts/confirmation-illustrations-final/selection-receipt.json) binds the pre-execution rule and final manifest.''',
'FINAL_NATIVE_INVENTORY':'''The original candidate campaign completed eight studies and 32 native attempts, totaling 1,984 offered requests and 4,104.999705749 seconds (68.42 minutes) of enclosing queue execution. It includes 200 unique original record tables: eight shared by the two closed diagnoses, 32 fit, 32 calibration and 128 shared across all confirmation policies. Development, repeated attempts and reused policy populations are not extra independent confirmation samples. All original native requests completed before the unchanged deadline and within the 2,000-request and 180-minute ceilings. The complete [final tables](publication/tables/final/analysis.json), including requests, paired outcomes, route counts, repetition stability, oracle strata and cost scopes, preserve every offered observation.''',
'SKEPTICAL_REPRODUCTION_SCOPE':'''This manuscript reports the original observations and the completed portable recomputation of those retained outputs. A separately assigned skeptical native reproduction, if performed, must retain its own request inventory, settings, provenance, costs and disagreements; it is not included in the original 1,984 requests or presented here as already completed. Its final report should be read alongside this manuscript.'''
}
rows=list(csv.DictReader((analysis/'attempts.csv').open()));cost=list(csv.DictReader((analysis/'cost-scopes.csv').open()))
lines=['All table entries are actual 128-question attempt totals. Each cell with a slash gives AB / BA; timing is descriptive because every policy fails quality eligibility.','','| Study | Full wall, seconds | Candidate wall, seconds | Full / candidate prompt tokens per repetition | Full / candidate generated tokens | Full / candidate qualified count |','| --- | ---: | ---: | ---: | ---: | ---: |']
for policy,label in [('slice','Always slice'),('simple','Simple gate'),('learned','Fitted: all full')]:
 r=[x for x in rows if x['study']=='negative-confirm-'+policy+'-study04'];b=sorted([x for x in r if x['arm']=='baseline'],key=lambda x:x['pair_index']);c=sorted([x for x in r if x['arm']=='candidate'],key=lambda x:x['pair_index'])
 lines.append(f"| {label} | {float(b[0]['full_wall_s']):.3f} / {float(b[1]['full_wall_s']):.3f} | {float(c[0]['full_wall_s']):.3f} / {float(c[1]['full_wall_s']):.3f} | {int(b[0]['prompt_tokens']):,} / {int(c[0]['prompt_tokens']):,} | {b[0]['generated_tokens']} / {c[0]['generated_tokens']} | {b[0]['slo_qualified']} / {c[0]['slo_qualified']} |")
lines.extend(['','Dependency slicing removes 61.79% of prompt tokens, while generated tokens rise from 545 to 550 per attempt. The simple gate removes 22.33% of prompt tokens. The learned controller preserves every full input and token count, yet its candidate/full wall ratios differ from one (about 0.971 and 0.793). This observed timing variation with identical prompts prevents attributing its lower candidate time to compression or learning. Sequential policies and shared-host scheduling limit causal timing comparisons.','','End-to-end p95 ranges are 245.288–249.460 seconds for the slice study full arms and 122.995–123.011 for slice; 245.299–246.520 for the simple study full arms and 204.230–207.837 for the gate; 262.341–325.787 for the fitted study full arms and 253.033–257.571 for its identical-input candidates. Arrival-based qualified counts are only 1/128 for each full arm, 6/128 for slice, 3/128 for simple and 1/128 for fitted. These low service fractions and failed absolute accuracy are retained alongside all timing values.','','The slice, simple and fitted confirmation queue executions take 800.030817060, 972.520437157 and 1,178.974084709 seconds. The last retained producer allocation observation is 31,200.174988555 seconds (8.67 hours) since the original allocation start, including earlier work, development and waiting; this is not a native-only total. Detailed, overlapping timing scopes remain in [cost-scopes.csv](publication/tables/final/cost-scopes.csv).'])
parts['CONFIRMATION_COSTS']='\n'.join(lines)
text=(own/'manuscript-negative-template04.md').read_text()
for key,value in parts.items():assert '{{'+key+'}}' in text;text=text.replace('{{'+key+'}}',value)
assert '{{' not in text
(docs/'manuscript.md').write_text(text)
shutil.copy2(own/'PUBLICATION-RERUN-final-template.md',docs/'PUBLICATION-RERUN.md')
(docs/'RERUN.md').write_text('# Reproduce the candidate study\n\nUse [PUBLICATION-RERUN.md](PUBLICATION-RERUN.md) for the complete, tested export layout, all eight actual studies, standard-library outcome and native-training validation, prospective illustrations and standalone figures. The stable final manifest is the complete-package interface. Earlier staged scripts and receipts remain labeled provenance.\n')
p=docs/'06-fresh-slice-confirmation.md';t=p.read_text();t+='\n\nFinal status: all three frozen policies subsequently completed. This document retains the first-study snapshot; the [final manuscript](manuscript.md) and [eight-export final analysis](publication/tables/final/analysis.json) supersede its interim campaign totals. No policy, seed or threshold changed.\n';p.write_text(t)
print(json.dumps({'status':'PASS','tables':len(list(out.iterdir())),'reviewed_binary_assets':len(assets),'manuscript_words':len(text.split())}))
